from __future__ import annotations

from typing import Protocol

from manimux.types import RobotCommand, RobotState


class RobotDriver(Protocol):
    def connect(self) -> None: ...

    def get_state(self) -> RobotState: ...

    def send_command(self, command: RobotCommand) -> None: ...

    def home(self) -> None: ...

    def stop(self) -> None: ...

    def close(self) -> None: ...
